### ISSUE TITLE
 JSON Decode failing

### ISSUE THREAD

**Issue by andrew521** [guoarthur/Kijiji-Repost-Headless#38] opened 2017-08-01 22:16 UTC
It stopped working today at 9am

# python3.6 /root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py repost_folder some-folder
Existing ad deleted before reposting
401
Traceback (most recent call last):
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 155, in <module                                  >
    main()
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 48, in main
    args.function(args)
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 142, in repost_                                  folder
    repost_ad(args)
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 134, in repost_                                  ad
    post_ad(args)
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_cmd.py", line 88, in post_ad
    api.post_ad_using_data(data, imageFiles)
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 154, in post_ad                                  _using_data
    imageList = self.upload_image(image_upload_token, imageFiles)
  File "/root/Kijiji-Repost-Headless-master/kijiji_repost_headless/kijiji_api.py", line 132, in upload_                                  image
    imageTree = json.loads(r.text)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by guoarthur** [comment] 2017-08-02 00:18
Duplicate of  #37

**Closed** 2017-08-02 00:17 UTC
