### ISSUE TITLE
Help - Example Car Post 

### ISSUE THREAD

**Issue by cerberii** [guoarthur/Kijiji-Repost-Headless#40] opened 2017-08-12 20:15 UTC
cars also dont work, need to put proper model, see motorcycle issue

**Comment by cerberii** [comment] 2017-08-12 20:17
here is new errors with some stuff cleared up, how do i fix the errorDate and youtube errors?  what about VIN errors? 

        Kj.extVars.validationMessages.errorDate = 'Please enter a valid date.';
        Kj.extVars.validationMessages.errorEventTime = 'The event end time cannot be earlier than the event start time.';
        Kj.extVars.validationMessages.maxDuration = "The duration cannot be longer than [X] days.";
        Kj.extVars.validationMessages.errorYoutube = 'You must enter a valid Youtube URL';
        Kj.extVars.validationMessages.errorWebsite = "Website URL is invalid, please check your input.";
        Kj.extVars.validationMessages.errorPostalCode = "Please provide a valid Postal Code.";
        Kj.extVars.validationMessages.errorVIN = "We're sorry, this is not a valid VIN.";
        Kj.extVars.validationMessages.errorCarproofURL = "We're sorry, this URL is not a valid CARPROOF report.";
        Kj.extVars.validationMessages.errorVINmismatch = "The VINs you have entered are not all the same.";
        Kj.extVars.validationMessages.emptyCell = "Please enter information above.";
        Kj.extVars.validationMessages.noResultsVIN = "No results found. Please check your VIN number.";
        Kj.extVars.validationMessages.postAdErrors = "Please fix the errors on the page";
        Kj.extVars.validationMessages.vagueAddress = "Please provide a more accurate address";
        Kj.extVars.validationMessages.missingPostal = "We cannot find that postal code";
        Kj.extVars.chooseTrim = "Please choose a trim level";
        Kj.extVars.featureAdded = "You have added this feature.";
        Kj.extVars.tracking.pageActionTitle = 'Post';

**Comment by guoarthur** [comment] 2017-08-23 02:19
Closing since it's a duplicate of #35

**Closed by guoarthur** 2017-08-23 02:19 UTC
Labels: bug
